### ISSUE TITLE
5G模块需求

### ISSUE THREAD

**Issue by XiaBai0601** [Jejz168/OpenWrt#1]
大佬，x86能给添加一些支持5G模块的驱动吗？

**Comment by Jejz168** [comment]
要什么内核的？

**Comment by XiaBai0601** [comment]
> 现在好像只支持rm500q-gl和rm500u-cn的，要什么内核的？带不带docker

内核6.1 不用docker 正好我的是rm500q-gl (不过是usb转m.2)应该可以的吧？ 麻烦你了！🙏🏻

**Comment by XiaBai0601** [comment]
感谢大佬！！已经用上了！！！🐮🍺

**Comment by Jejz168** [comment]
> 感谢大佬！！已经用上了！！！🐮🍺

能用吗？

**Comment by XiaBai0601** [comment]
> > 感谢大佬！！已经用上了！！！🐮🍺
> 
> 能用吗？我没得测试

可以的 刚刚我试过了 qmi模式下 能正常用
