### ISSUE TITLE
ikoolproxy的https引擎没有启动成功，无法下载证书。

### ISSUE THREAD

**Issue by ilxp** [Jejz168/OpenWrt#2]
系统日志是：
Tue Oct 10 08:40:29 2023 kern.info kernel: [ 1133.303376] koolproxy[26099]: segfault at 1b58 ip 000000000040f5cc sp 00007fb0b2d0a938 error 4 in koolproxy[401000+103000] likely on CPU 2 (core 2, socket 0)
Tue Oct 10 08:40:29 2023 kern.info kernel: [ 1133.317522] Code: c3 66 66 2e 0f 1f 84 00 00 00 00 00 66 90 48 8b 47 48 8b b8 f8 03 00 00 e9 0e d6 0e 00 90 48 8b 05 c9 a3 19 00 be e8 51 50 00 <8b> 90 58 1b 00 00 48 8d 88 58 0b 00 00 31 c0 e9 55 83 0e 00 48 85
有办法解决吗。大佬。

Tue Oct 10 08:31:33 2023 daemon.info koolproxy[26069]: init https engine
Tue Oct 10 08:31:33 2023 daemon.info koolproxy[26069]: https engine: mbedtls_pk_parse_key issuer failed: -11904
Tue Oct 10 08:31:33 2023 daemon.info koolproxy[26069]: init https engine failed:-3, go with http mode only

**Comment by Jejz168** [comment]
应该是op更新的问题。我也没有解决办法
