### ISSUE TITLE
急急急

### ISSUE THREAD

**Issue by Riley259** [Jejz168/OpenWrt#4]
大佬在使用外网链接的时候进不去ssh和网页登陆并且会频繁掉线不管手机或者电脑，求大佬修复并且可以加上doker和在线自动定时的功能嘛，求了，本人x86

**Comment by Jejz168** [comment]
ssh我这远程没问题，系统--定时重启，docker之前总有点问题，所以没做了

**Comment by Riley259** [comment]
> ssh我这远程没问题，系统--定时重启，docker之前总有点问题，所以没做了

呃不对应该是在线自动定时更新功能
